site_name: TaskTime - Documentatie
site_description: 'TaskTime Documentatie'
site_author: 'CipherCore'
docs_dir: docs/
repo_name: 'genego-dev/wiki.tasktime.eu'
repo_url: 'https://github.com/genego-dev/wiki.tasktime.eu'
nav:
    - Introductie: index.md
    - Features: features.md
    - Handleiding: handleiding.md
    - Koppeling (API) : koppeling.md
theme:
  name: 'material'
  

name: Deploy MkDocs
uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
